"""Chat app: POST /chat {message}, the shop's support assistant.

Approved patches for the message field are written as Python between the
AUTO-PATCHES markers below (by chameleon.patch.integrate, from the Redis patch
store) and run before the message reaches the assistant.
Run alone: uvicorn chameleon.apps.chat_app:app --port 8204
"""
from __future__ import annotations

from fastapi import APIRouter, FastAPI
from pydantic import BaseModel

from .patchkit import PatchSet, deny, normalize  # noqa: F401 - used by the generated patches

patches = PatchSet()

# >>> CHAMELEON AUTO-PATCHES BEGIN >>> generated by chameleon.patch.integrate; edits here are overwritten
# (no approved patches yet)
# <<< CHAMELEON AUTO-PATCHES END <<<


class ChatRequest(BaseModel):
    message: str


router = APIRouter()


@router.post("/chat")
def chat(req: ChatRequest):
    patches.check({"message": req.message})
    return {"reply": f"Thanks for your message! (demo assistant) You said: {req.message[:200]}"}


app = FastAPI(title="Chameleon Edge demo: chat")
app.include_router(router)
