"""Files app: GET /files?name=...

Deliberately weak until patched: a traversal-shaped name returns fake,
canary-tagged content (never the real filesystem), so a successful attack is
detectable. Approved patches for the name field are written as Python between
the AUTO-PATCHES markers below (by chameleon.patch.integrate, from the Redis
patch store) and close the hole.
Run alone: uvicorn chameleon.apps.files_app:app --port 8203
"""
from __future__ import annotations

import re

from fastapi import APIRouter, FastAPI, HTTPException

from .patchkit import PatchSet, deny, normalize  # noqa: F401 - used by the generated patches

patches = PatchSet()

# >>> CHAMELEON AUTO-PATCHES BEGIN >>> generated by chameleon.patch.integrate; edits here are overwritten
# patch path-traversal-5 (61547c5f): path-traversal. Rule written by Qwen3-Next-80B on the Nano; passed the replay, URL-encoding,
# normal-traffic and ReDoS tests and review by Gemma 4 12B before it was rendered here.
@patches.guard(rule_id='path-traversal-5', patch_id='61547c5f-8fde-49e8-bce6-1c175d30c487', attack_type='path-traversal',
               fields=('name',),
               description='Blocks common path traversal patterns including dot sequences, double slashes, hex-encoded dots, and known target files, while avoiding false positives on benign names.')
def path_traversal_5_61547c5f(value: str) -> bool:
    pattern = r'(\.\./|/{2,}|0x2e0x2e|\.\.{2,}|web-inf/web\.xml|/iii\{file\}|^\.\.|^\.\./|/\.\.|\.{3,}|/etc/passwd|/var/www/html/\.\./\.\./\.\./etc/passwd)'
    return deny(pattern, normalize(value))  # URL-decoded + lowercased first
# <<< CHAMELEON AUTO-PATCHES END <<<

CANARY_API_KEY = "CANARY-APIKEY-9d4e6a1f2c"

SAFE_FILES = {
    "readme.txt": "Welcome to the demo shop.",
    "changelog.txt": "v1.0 initial release",
}

# Only returned when a request looks like it's trying to escape SAFE_FILES;
# content is fake, but the embedded token lets us detect the leak downstream.
CANARY_FILE_CONTENT = f"root:x:0:0:root:/root:/bin/bash\n# leaked api_key={CANARY_API_KEY}\n"

TRAVERSAL_HINT = re.compile(r"\.\./|%2e%2e|/etc/|\\windows\\", re.IGNORECASE)

router = APIRouter()


@router.get("/files")
def files(name: str = ""):
    patches.check({"name": name})
    if name in SAFE_FILES:
        return {"name": name, "content": SAFE_FILES[name]}
    if TRAVERSAL_HINT.search(name):
        return {"name": name, "content": CANARY_FILE_CONTENT}
    raise HTTPException(status_code=404, detail="file not found")


app = FastAPI(title="NanoPot demo: files")
app.include_router(router)
