"""Login app: POST /login {username, password}.

Approved patches for the username/password fields are written as Python
between the AUTO-PATCHES markers below (by chameleon.patch.integrate, from the
Redis patch store) and run before the credentials are checked.
Run alone: uvicorn chameleon.apps.login_app:app --port 8201
"""
from __future__ import annotations

from fastapi import APIRouter, FastAPI
from pydantic import BaseModel

from .patchkit import PatchSet, deny, normalize  # noqa: F401 - used by the generated patches

patches = PatchSet()

# >>> CHAMELEON AUTO-PATCHES BEGIN >>> generated by chameleon.patch.integrate; edits here are overwritten
# patch sqli-5 (7e801989): sqli. Rule written by Qwen3-Next-80B on the Nano; passed the replay, URL-encoding,
# normal-traffic and ReDoS tests and review by Gemma 4 12B before it was rendered here.
@patches.guard(rule_id='sqli-5', patch_id='7e801989-83f2-4f24-98a7-e516a5d2600c', attack_type='sqli',
               fields=('username',),
               learned_from="admin' OR '1'='1' --",
               description="Blocks SQLi OR-based conditions like 'OR 1=1', 'OR 'a'='a', 'OR 2=2', etc., with common terminators and optional quotes around literals")
def sqli_5_7e801989(value: str) -> bool:
    pattern = r'''\bor\s*['"]?\s*(?:\d+|['"]\w['"])?\s*=\s*['"]?\s*(?:\d+|['"]\w['"])?\s*(?:--|#|/\*|;|\s*$)'''
    return deny(pattern, normalize(value))  # URL-decoded + lowercased first
# <<< CHAMELEON AUTO-PATCHES END <<<

CANARY_ADMIN_PASSWORD = "CANARY-ADMIN-7f3a9c2e1b"

USERS = {
    "admin": CANARY_ADMIN_PASSWORD,
    "jsmith": "hunter2",
}


class LoginRequest(BaseModel):
    username: str
    password: str


router = APIRouter()


@router.post("/login")
def login(req: LoginRequest):
    patches.check({"username": req.username, "password": req.password})
    return {"ok": USERS.get(req.username) == req.password}


app = FastAPI(title="Chameleon Edge demo: login")
app.include_router(router)
