"""Login app: POST /login {username, password}.

Approved patches for the username/password fields are written as Python
between the AUTO-PATCHES markers below (by chameleon.patch.integrate, from the
Redis patch store) and run before the credentials are checked.
Run alone: uvicorn chameleon.apps.login_app:app --port 8201
"""
from __future__ import annotations

from fastapi import APIRouter, FastAPI
from pydantic import BaseModel

from .patchkit import PatchSet, deny, normalize  # noqa: F401 - used by the generated patches

patches = PatchSet()

# >>> CHAMELEON AUTO-PATCHES BEGIN >>> generated by chameleon.patch.integrate; edits here are overwritten
# (no approved patches yet)
# <<< CHAMELEON AUTO-PATCHES END <<<

CANARY_ADMIN_PASSWORD = "CANARY-ADMIN-7f3a9c2e1b"

USERS = {
    "admin": CANARY_ADMIN_PASSWORD,
    "jsmith": "hunter2",
}


class LoginRequest(BaseModel):
    username: str
    password: str


router = APIRouter()


@router.post("/login")
def login(req: LoginRequest):
    patches.check({"username": req.username, "password": req.password})
    return {"ok": USERS.get(req.username) == req.password}


app = FastAPI(title="Chameleon Edge demo: login")
app.include_router(router)
