"""Search app: GET /search?q=...

Approved patches for the q field are written as Python between the
AUTO-PATCHES markers below (by chameleon.patch.integrate, from the Redis patch
store) and run before the query is used.
Run alone: uvicorn chameleon.apps.search_app:app --port 8202
"""
from __future__ import annotations

from fastapi import APIRouter, FastAPI

from .patchkit import PatchSet, deny, normalize  # noqa: F401 - used by the generated patches

patches = PatchSet()

# >>> CHAMELEON AUTO-PATCHES BEGIN >>> generated by chameleon.patch.integrate; edits here are overwritten
# (no approved patches yet)
# <<< CHAMELEON AUTO-PATCHES END <<<

PRODUCTS = [
    {"id": 1, "name": "blue shirt", "price": 19.99},
    {"id": 2, "name": "red shoes", "price": 49.99},
    {"id": 3, "name": "green hat", "price": 12.5},
]

router = APIRouter()


@router.get("/search")
def search(q: str = ""):
    patches.check({"q": q})
    ql = q.lower()
    return {"results": [p for p in PRODUCTS if ql in p["name"].lower()]}


app = FastAPI(title="NanoPot demo: search")
app.include_router(router)
