"""Search app: GET /search?q=...

Approved patches for the q field are written as Python between the
AUTO-PATCHES markers below (by chameleon.patch.integrate, from the Redis patch
store) and run before the query is used.
Run alone: uvicorn chameleon.apps.search_app:app --port 8202
"""
from __future__ import annotations

from fastapi import APIRouter, FastAPI

from .patchkit import PatchSet, deny, normalize  # noqa: F401 - used by the generated patches

patches = PatchSet()

# >>> CHAMELEON AUTO-PATCHES BEGIN >>> generated by chameleon.patch.integrate; edits here are overwritten
# patch sqli-2 (6b74c437): sqli. Rule written by Qwen3-Next-80B on the Nano; passed the replay, URL-encoding,
# normal-traffic and ReDoS tests and review by Gemma 4 12B before it was rendered here.
@patches.guard(rule_id='sqli-2', patch_id='6b74c437-0df3-412b-b1aa-bb0ee9e7f9b5', attack_type='sqli',
               fields=('q',),
               learned_from='1 union select username, password from users--',
               description='Blocks SQLi attempts containing UNION followed by SELECT with optional non-alphanumeric separators')
def sqli_2_6b74c437(value: str) -> bool:
    pattern = r'\bunion\s*[^a-z0-9]*\s*select\b'
    return deny(pattern, normalize(value))  # URL-decoded + lowercased first
# <<< CHAMELEON AUTO-PATCHES END <<<

PRODUCTS = [
    {"id": 1, "name": "blue shirt", "price": 19.99},
    {"id": 2, "name": "red shoes", "price": 49.99},
    {"id": 3, "name": "green hat", "price": 12.5},
]

router = APIRouter()


@router.get("/search")
def search(q: str = ""):
    patches.check({"q": q})
    ql = q.lower()
    return {"results": [p for p in PRODUCTS if ql in p["name"].lower()]}


app = FastAPI(title="Chameleon Edge demo: search")
app.include_router(router)
