"""Render approved patches into the four demo apps as Python code.

Each app file (chameleon/apps/{login,search,files,chat}_app.py) has an
AUTO-PATCHES block. On every change to the active patch set, the block in each
file is regenerated from scratch from the active patches -- so rollbacks and
resets remove code as cleanly as approvals add it, and regenerating twice
changes nothing.

Only verified rules are rendered, through a fixed template: the model chose the
regex, never the code. Every value from the rule (pattern, ids, the attack it
came from) enters the source through repr(), which always yields a plain Python
string literal, and the new file must compile() before it replaces the old one.
"""
from __future__ import annotations

import ast
import json
import logging
import os
import re
import tempfile
import warnings
from pathlib import Path

from .. import config
from . import redis_store

log = logging.getLogger(__name__)

ENABLED = True  # tests switch this off so they never rewrite the real app files

APP_FIELDS = {
    "login_app.py": ("username", "password"),
    "search_app.py": ("q",),
    "files_app.py": ("name",),
    "chat_app.py": ("message",),
}
BEGIN = "# >>> CHAMELEON AUTO-PATCHES BEGIN >>>"
END = "# <<< CHAMELEON AUTO-PATCHES END <<<"
_BLOCK = re.compile(re.escape(BEGIN) + r"[^\n]*\n.*?" + re.escape(END), re.DOTALL)
EMPTY = "# (no approved patches yet)"


def _ident(text: str) -> str:
    return re.sub(r"[^0-9a-zA-Z_]", "_", text).strip("_").lower() or "patch"


def _oneline(text: str, limit: int = 160) -> str:
    return " ".join(str(text).split())[:limit]


def literal(text: str) -> str:
    """The most readable Python literal for `text` -- a raw string when one
    round-trips exactly (regexes are full of backslashes), else repr()."""
    for q in ("'", '"', "'''", '"""'):
        candidate = f"r{q}{text}{q}"
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", SyntaxWarning)  # rejected candidates may warn
                if "\n" not in text and ast.literal_eval(candidate) == text:
                    return candidate
        except (SyntaxError, ValueError):
            pass
    return repr(text)


def files_for(rule: dict) -> list[str]:
    field = rule.get("field", "*")
    return [f for f, fields in APP_FIELDS.items() if field == "*" or field in fields]


def render(patch: dict) -> str:
    """Python source for one patch. `patch` has id, rule_json, and optionally
    learned_from."""
    rule = json.loads(patch["rule_json"]) if isinstance(patch.get("rule_json"), str) else patch["rule"]
    pid = str(patch["id"])
    name = f"{_ident(rule['id'])}_{_ident(pid[:8])}"
    check = ("deny(pattern, normalize(value))  # URL-decoded + lowercased first"
             if rule["type"] == "normalize_then_deny" else "deny(pattern, value)")
    learned = _oneline(patch.get("learned_from", ""), 200)
    lines = [
        f"# patch {_oneline(rule['id'], 40)} ({pid[:8]}): {_oneline(rule.get('attack_type', ''), 40)}."
        " Rule written by Qwen3-Next-80B on the Nano; passed the replay, URL-encoding,",
        "# normal-traffic and ReDoS tests and review by Gemma 4 12B before it was rendered here.",
        f"@patches.guard(rule_id={rule['id']!r}, patch_id={pid!r}, attack_type={rule.get('attack_type', '')!r},",
        f"               fields=({rule.get('field', '*')!r},),",
    ]
    if learned:
        lines.append(f"               learned_from={learned!r},")
    lines += [
        f"               description={_oneline(rule.get('description', ''), 200)!r})",
        f"def {name}(value: str) -> bool:",
        f"    pattern = {literal(rule['pattern'])}",
        f"    return {check}",
    ]
    return "\n".join(lines)


def render_block(patches: list[dict]) -> str:
    inner = "\n\n".join(render(p) for p in patches) if patches else EMPTY
    return f"{BEGIN} generated by chameleon.patch.integrate; edits here are overwritten\n{inner}\n{END}"


def _write_if_changed(path: Path, source: str) -> bool:
    if path.read_text() == source:
        return False
    compile(source, str(path), "exec")  # never install a file that doesn't parse
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    with os.fdopen(fd, "w") as f:
        f.write(source)
    os.replace(tmp, path)
    return True


def sync(patches: list[dict], apps_dir: Path | None = None) -> dict[str, int]:
    """Regenerate every app's AUTO-PATCHES block from `patches`. Returns
    {file: number of patches installed}."""
    apps_dir = Path(apps_dir or config.APPS_DIR)
    installed = {}
    for filename in APP_FIELDS:
        path = apps_dir / filename
        mine = [p for p in patches if filename in files_for(
            json.loads(p["rule_json"]) if isinstance(p.get("rule_json"), str) else p["rule"])]
        source = path.read_text()
        if not _BLOCK.search(source):
            raise ValueError(f"{path} has no AUTO-PATCHES block")
        _write_if_changed(path, _BLOCK.sub(lambda _m: render_block(mine), source, count=1))
        installed[filename] = len(mine)
    return installed


def active_patches(conn) -> list[dict]:
    """The enforced patches: from Redis when it's up, else SQLite."""
    from_redis = redis_store.active_patches()
    if from_redis is not None:
        return from_redis
    rows = conn.execute(
        "SELECT id, rule_json, writer_model, created_at FROM patches WHERE status = 'approved' ORDER BY created_at"
    ).fetchall()
    return [dict(r) for r in rows]


def sync_active(conn) -> dict[str, int] | None:
    """Bring the app files in line with the active patch set, and record each
    patch's code and target files in Redis. Never raises: a failure here must
    not undo an approval that is already enforced at the front door."""
    if not ENABLED:
        return None
    try:
        patches = active_patches(conn)
        installed = sync(patches)
        for p in patches:
            rule = json.loads(p["rule_json"])
            redis_store.annotate(p["id"], python_code=render(p), app_files=",".join(files_for(rule)))
        return installed
    except Exception as exc:  # noqa: BLE001
        log.warning("integrating patches into the app files failed: %s: %s", type(exc).__name__, exc)
        return None
